// Generated by CoffeeScript 1.6.3
  var devuelve_md5, md5, message, str2hex, sum, _i, _len, _ref;

  sum = function(array) {
    return array.reduce(function(x, y) {
      return x + y;
    });
  };

  md5 = (function() {
    var K, i, lrot, s;
    s = [738695, 669989, 770404, 703814];
    s = (function() {
      var _i, _results;
      _results = [];
      for (i = _i = 0; _i <= 63; i = ++_i) {
        _results.push(s[i >> 4] >> i % 4 * 5 & 31);
      }
      return _results;
    })();
    K = (function() {
      var _i, _results;
      _results = [];
      for (i = _i = 1; _i <= 64; i = ++_i) {
        _results.push(Math.floor(Math.pow(2, 32) * Math.abs(Math.sin(i))));
      }
      return _results;
    })();
    lrot = function(x, y) {
      return x << y | x >>> 32 - y;
    };
    return function(input) {
      var A, B, C, D, F, M, a0, b0, c0, d0, g, j, len, x, y, _i, _j, _ref, _ref1, _ref2, _ref3;
      d0 = 0x10325476;
      a0 = 0x67452301;
      b0 = ~d0;
      c0 = ~a0;
      M = (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = input.length; _i < _ref; i = _i += 4) {
          _results.push(sum((function() {
            var _j, _results1;
            _results1 = [];
            for (j = _j = 0; _j <= 3; j = ++_j) {
              _results1.push(input.charCodeAt(i + j) << j * 8);
            }
            return _results1;
          })()));
        }
        return _results;
      })();
      len = input.length * 8;
      M[len >> 5] |= 128 << len % 32;
      M[(len + 64 >>> 9 << 4) + 14] = len;
      for (x = _i = 0, _ref = M.length; _i < _ref; x = _i += 16) {
        _ref1 = [a0, b0, c0, d0], A = _ref1[0], B = _ref1[1], C = _ref1[2], D = _ref1[3];
        for (i = _j = 0; _j <= 63; i = ++_j) {
          if (i < 16) {
            F = B & C | ~B & D;
            g = i;
          } else if (i < 32) {
            F = B & D | C & ~D;
            g = i * 5 + 1;
          } else if (i < 48) {
            F = B ^ C ^ D;
            g = i * 3 + 5;
          } else {
            F = C ^ (B | ~D);
            g = i * 7;
          }
          _ref3 = [D, B + lrot(A + F + K[i] + ((_ref2 = M[x + g % 16]) != null ? _ref2 : 0), s[i]), B, C], A = _ref3[0], B = _ref3[1], C = _ref3[2], D = _ref3[3];
        }
        a0 += A;
        b0 += B;
        c0 += C;
        d0 += D;
      }
      return ((function() {
        var _k, _len, _ref4, _results;
        _ref4 = [a0, b0, c0, d0];
        _results = [];
        for (_k = 0, _len = _ref4.length; _k < _len; _k++) {
          x = _ref4[_k];
          _results.push(((function() {
            var _l, _results1;
            _results1 = [];
            for (y = _l = 0; _l <= 3; y = ++_l) {
              _results1.push(String.fromCharCode(x >>> 8 * y & 255));
            }
            return _results1;
          })()).join(''));
        }
        return _results;
      })()).join('');
    };
  })();

  str2hex = (function() {
    var hex, x;
    hex = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'];
    hex = (function() {
      var _i, _results;
      _results = [];
      for (x = _i = 0; _i <= 255; x = ++_i) {
        _results.push(hex[x >> 4] + hex[x & 15]);
      }
      return _results;
    })();
    return function(str) {
      var c;
      return ((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = str.length; _i < _len; _i++) {
          c = str[_i];
          _results.push(hex[c.charCodeAt()]);
        }
        return _results;
      })()).join('');
    };
  })();

  devuelve_md5 = function(texto) {
    return str2hex(md5(texto));
  };
  


